### ISSUE TITLE
Dodać testy statystyczne

### ISSUE THREAD

**Issue by kasztanka** [pmiara/Sequence-Classification#22]
Testy statystyczne
- Anova - dla każdego zbioru danych na wszystkich klasyfikatorach
- Friedmana - dla wszystkich zbiorów na wszystkich klasyfikatorach

**Comment by piotermiarer** [comment]
Link do artykułu: [link](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.141.3142&rep=rep1&type=pdf)

**Comment by kasztanka** [comment]
Czego nam jeszcze brakuje:
- sprawdzenie założeń do Anovy:
* https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.shapiro.html
* https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.levene.html
- dla 2 algorytmów zamiast Friedmana: https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.wilcoxon.html

Ewentualnie możemy też dodać Kruskala-Wallisa, gdy założenia Anovy nie są spełnione (o ile dobrze rozumiem): https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kruskal.html
